version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
    groups:
      github-actions-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: UTC
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    groups:
      production-minor-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-minor-patch:
        dependency-type: development
        update-types:
          - minor
          - patch
